0.79 devel-2

diff --git a/dvdisaster/scripts/bash-based-configure b/dvdisaster/scripts/bash-based-configure
--- a/dvdisaster/scripts/bash-based-configure
+++ b/dvdisaster/scripts/bash-based-configure
@@ -56,13 +56,14 @@
 # EXECUTE_PROGRAM	Invoke a command to see if a certain program is available
 #
 # CHECK_ENDIAN		Test whether system is little or big endian
+# CHECK_BITNESS		Test whether system is 32bit or 64bit
 # CHECK_SSE2		Test whether when can compile for SSE2 extensions
 # FINALIZE_HELP		Finish --help output (optional, but user friendly)
 #
 # WITH_OPTION name default  adds -DWITH_OPTION_VALUE for -with-option=value args
 #			    to CFG_WITH_OPTIONS,
 
-CONFIGURE_VERSION="0.55"
+CONFIGURE_VERSION="0.56"
 
 echo "Bash based configure V$CONFIGURE_VERSION"
 echo
@@ -1729,7 +1730,70 @@ EOF
 	   ;;
       esac
   fi
+}
 
+#
+# Figure out bitness of system
+#
+
+function CHECK_BITNESS()
+{
+   if test -n "$cfg_help_mode"; then
+     echo " --with-bitness=[32 | 64]"
+     return 0
+   fi
+
+   echo -e "\n/* *** CHECK_BITNESS */\n" >>$LOGFILE
+   echo -n "Checking bitness..."
+
+   # See if user wants to override our test
+
+   if test -n "$cfg_with_bitness"; then
+      case "$cfg_with_bitness" in
+	32) echo " 32bit (user supplied)"
+	        CFG_HAVE_OPTIONS="$CFG_HAVE_OPTIONS -DHAVE_32BIT"
+	        ;;
+	64) echo " 64bit (user supplied)"
+	        CFG_HAVE_OPTIONS="$CFG_HAVE_OPTIONS -DHAVE_64BIT"
+	        ;;
+        *) echo -e " $cfg_with_bitness (illegal value)\n"
+	   echo "Please use one of the following values:"
+	   echo "--with-bitness=[32 | 64]"
+	   exit 1
+	   ;;
+      esac
+      return 0;
+   fi
+
+   # Try automatic detection
+
+   cat > conftest.c <<EOF
+int main()
+{  switch(sizeof(char*))
+   {  case 4: printf("32\n"); break;
+      case 8: printf("64\n"); break;
+      default: printf("failure\n"); break;
+   }
+}
+EOF
+
+   if try_compile; then
+      bitness=`./conftest`
+      case "$bitness" in
+	32) echo " 32bit"
+	        CFG_HAVE_OPTIONS="$CFG_HAVE_OPTIONS -DHAVE_32BIT"
+	        ;;
+	64) echo " 64bit"
+	        CFG_HAVE_OPTIONS="$CFG_HAVE_OPTIONS -DHAVE_64BIT"
+	        ;;
+        *) echo -e " error\n"
+	   echo "System bitness could not be determined."
+	   echo "Please specify one using the following option:"
+	   echo "--with-bitness=[32|64]"
+	   exit 1
+	   ;;
+      esac
+  fi
 }
 
 #
